import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Featured from '../components/Featured';
import ProductList from '../components/ProductList';

const Home = () => {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title> Food Ordering App </title>
                    <meta
                        name="description"
                        content="Generated by nextjs Food Ordering App"
                    />
                    <link
                        rel="stylesheet"
                        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
                        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
                        crossorigin="anonymous"
                        referrerpolicy="no-referrer"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Featured />
                <ProductList />
            </div>
        </>
    );
};

export default Home;
