import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Featured from '../components/Featured';
import ProductList from '../components/ProductList';
import axios from 'axios';

const Home = ({productList}) => {
    return (
        <div className={styles.container}>
            <Head>
                <title> Food Ordering App </title>
                <meta
                    name="description"
                    content="Generated by nextjs Food Ordering App"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Featured />
            <ProductList productList={productList} />
        </div>
    );
};

export default Home;

export const getServerSideProps = async () => {
    const res = await axios.get('http://localhost:3000/api/products');
    return {
        props: {
            productList: res.data,
        },
    };
};
