import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Featured from '../components/Featured';
import ProductList from '../components/ProductList';
import axios, {AxiosResponse} from 'axios';
import {useState} from 'react';
import AddButton from '../components/AddButton';
import Add from '../components/Add';
import {GetServerSideProps} from 'next';
import {NextApiRequestCookies} from 'next/dist/server/api-utils';
import {Products} from '../interface/Interface';

const Home = ({productList, admin}): JSX.Element => {
    const [close, setClose] = useState<boolean>(true);
    return (
        <div className={styles.container}>
            <Head>
                <title> Food Ordering App </title>
                <meta
                    name="description"
                    content="Generated by nextjs Food Ordering App"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Featured />
            {admin && <AddButton setClose={setClose} />}
            <ProductList productList={productList} />
            {!close && <Add setClose={setClose} />}
        </div>
    );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
    const myCookie = context.req?.cookies.token || '';
    let admin = false;
    if (myCookie === process.env.TOKEN) {
        admin = true;
    }
    const res: AxiosResponse<Products> = await axios.get(
        'https://food-ordering-app-one.vercel.app/api/products',
    );
    return {
        props: {
            productList: res.data,
            admin,
        },
    };
};
