import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Featured from '../components/Featured';
import ProductList from '../components/ProductList';
import axios from 'axios';
import {useState} from 'react';
import AddButton from '../components/AddButton';
import Add from '../components/Add';

const Home = ({productList, admin}) => {
    const [close, setClose] = useState(true);
    return (
        <div className={styles.container}>
            <Head>
                <title> Food Ordering App </title>
                <meta
                    name="description"
                    content="Generated by nextjs Food Ordering App"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Featured />
            {admin && <AddButton setClose={setClose} />}
            <ProductList productList={productList} />
            {!close && <Add setClose={setClose} />}
        </div>
    );
};

export default Home;

export const getServerSideProps = async (context) => {
    const myCookie = context.req?.cookies || '';
    let admin = false;
    if (myCookie.token === process.env.TOKEN) {
        admin = true;
    }
    const res = await axios.get('http://localhost:3000/api/products');
    return {
        props: {
            productList: res.data,
            admin,
        },
    };
};
